version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - docker --version
  build:
    commands:
      - echo "Building Docker image"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
      - docker build -t portfolio .
      - export IMAGE_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portfolio:latest
      - docker tag portfolio:latest $IMAGE_URL
      - docker push $IMAGE_URL
      - sed -i "s|\${image_url}|$IMAGE_URL|g" "Dockerrun.aws.json"
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - Dockerrun.aws.json
    - app/build/*
    - logs/*
