version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - docker --version
  build:
    commands:
      - echo "Building Docker image"
      - $(aws ecr get-login-password --region $AWS_REGION) | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker build -t portfolio .
      - docker tag portfolio:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portfolio:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portfolio:latest
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - Dockerrun.aws.json
    - app/build/*
    - logs/*
