version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - docker --version
  build:
    commands:
      - docker build -t portfolio .
      - docker tag portfolio:latest jvmartyns/portfolio:latest
  post_build:
    commands:
      - echo "Post-build phase"

artifacts:
  files:
    - Dockerrun.aws.json
    - app/build/*
    - logs/*
