version: "3"
services:
  portfolio:
    container_name: portfolio
    build:
      context: .
    command: /bin/sh docker_dev_start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app/
    networks:
      - portfolio_network
    depends_on:
      - portfolio_db
    tty: true

  portfolio_db:
    container_name: portfolio_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: portfolio_dev
    ports:
      - "5432:5432"
    networks:
      - portfolio_network

networks:
  portfolio_network:
    name: portfolio_network
