# Generated by Django 4.2.1 on 2023-07-28 13:19

import core.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=core.models.images_path),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.FileField(upload_to=core.models.images_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=core.models.images_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=core.models.images_path),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='image',
            field=models.FileField(upload_to=core.models.images_path),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.FileField(upload_to=core.models.images_path),
        ),
    ]
